### PR TITLE
Visibility JS Bindings

### PR DESCRIPTION
**Pull request by DDRBoxman**

### CODE REVIEW

**Comment by notr1ch** [comment]
This seems to be based off an older commit, could you rebase it to HEAD so your changes are more clear?

**Comment by DDRBoxman** [comment]
Sorry about that, accidentally included a few extra non-essential tweaks I made.

**Comment by DDRBoxman** [comment]
Do we keep a version number for the browser plugin? I'd like to expose that in the js too.

**Comment by OsirisNL** [comment]
No, there is no version number being exposed.

**Pull request merged**
